# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTp9Ad9GvvJDcZKVI10V9kT5ABZRZP-E
"""

import tensorflow as tf 
from tensorflow import keras

pip install matplotlib

pip install pandas

import matplotlib.pyplot as plt

fmnist_data = keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = fmnist_data.load_data()

plt.imshow(x_train[0,], cmap="gray")

x_train, x_test = x_train/255.0 , x_test/255.0

x_train[1,]

#1-Make a Model Level is first step

model = keras.models.Sequential([
  (keras.layers.Flatten(input_shape = [28, 28])),
  (keras.layers.Dense(100, activation = "relu")),
  (keras.layers.Dense(75, activation = "relu")),
  (keras.layers.Dense(10, activation = "softmax"))
])

model.summary()

model.layers

weights, bias = model.layers[1].get_weights()

weights

bias

#2 - Compile Model : loss and optimization and different metrics are considerable

model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

#3 - Fit Model

pip install epochs

history = model.fit(x_train, y_train, epochs=50, validation_split=0.15)

